server:
  port: 8084

spring:
  application:
    name: spring-hazelcast

  datasource:
    driver-class-name: org.h2.Driver
    validation-query: select 1;

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        id:
          new_generator_mapping: true
          format_sql: true